import type { MetadataRoute } from 'next';

// Web app manifest — served by Next at /manifest.webmanifest and linked from every
// page automatically. Icons are generated by scripts/generate-pwa-icons.mjs.
//
// Colours are the light-theme cream (--color-bg). The manifest has no reliable
// dark variant, so the launch splash is always cream; once the page is running the
// <meta name="theme-color"> from layout.tsx (kept in sync with the in-app theme by
// components/pwa) takes over the title/status bar.
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/',
    name: 'Kafé OS',
    short_name: 'Kafé OS',
    description: 'ระบบขายหน้าร้าน (POS) สำหรับร้านกาแฟและคาเฟ่ — ขาย ครัว สต็อก และรายงานในแอปเดียว',
    lang: 'th',
    dir: 'ltr',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    // Counter tablets sit in landscape, phones in portrait — don't lock either.
    orientation: 'any',
    theme_color: '#F7F3EC',
    background_color: '#F7F3EC',
    categories: ['business', 'food', 'productivity'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
